import Head from "next/head";
import { Inter } from "next/font/google";
import { useEagerConnect, useInactiveListener } from "../lib/hooks/web3Hook";
import { Toaster } from "react-hot-toast";
import Heros from "../components/Heros";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const triedEager = useEagerConnect();
  useInactiveListener(!triedEager);

  return (
    <>
      <Toaster position="top-center" reverseOrder={false} />
      <Head>
        <title>XYXY-PRESALE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heros className={inter.className} />
      </main>
    </>
  );
}
